<a href="https://colab.research.google.com/github/Cory-Suhr/rush-sales-analysis-final-project/blob/main/Rush_Sales_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## GB885 Final Project

## Rush Sales Analysis

Cory Suhr

## Business Problem: You work as a sales analyst for RUSH, a globally renowned sportswear and footwear brand known for its innovative designs and performance-oriented products. The company stores its raw sales data as a collection of three tables:

TABLE_PRODUCTS
TABLE_RETAILER
TABLE_SALES
The data includes the number of units sold, the total sales revenue, the location of the sales, the type of product sold, as well as other relevant information. (For data field definitions and explanations, see the data dictionary.) The data is "raw," meaning it has not been cleaned and probably contains errors that need to be addressed.

The VP of US Sales has tasked you with analyzing sales data for trends and insights that will help company leadership understand the market and identify opportunities for growth. For example, you may want to look for trends or insights in seasonality, retailers, locations, or sales methods. Take initiative to apply your creativity and curiosity to this data.

In addition, she has asked you to answer the following business questions:

What product category (product) had the highest sales (in dollars) in 2021? How much did it sell?
What state had the highest sales (in dollars) of women's products in 2021? How much was it?
What state had the highest sales (in dollars) of men's products in 2021? How much was it?
What retailer purchased the most units in 2021? In 2020?

## Import Libraries

In [10]:
# Importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Load the Data

In [11]:
# Loading the data
products = pd.read_csv('/content/drive/MyDrive/TABLE_PRODUCTS_885.csv')
retailer = pd.read_csv('/content/drive/MyDrive/TABLE_RETAILER_885.csv')
sales = pd.read_csv('/content/drive/MyDrive/TABLE_SALES_885.csv')

## Initial Data Inspection

In [12]:
# Looking at some basics for  products

products.head()

         PRODUCT_ID|PRODUCT_NAME
0      020|Men's Street Footwear
1    030|Men's Athletic Footwear
2    120|Women's Street Footwear
3  130|Women's Athletic Footwear
4              040|Men's Apparel

In [14]:
## Products variable types
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 1 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   PRODUCT_ID|PRODUCT_NAME  6 non-null      object
dtypes: object(1)
memory usage: 180.0+ bytes

In [15]:
# Basics of retailor
retailer.head()

  RETAILER_ID RETAILER     REGION          STATE        CITY
0    A00MOHCO   Amazon    Midwest           Ohio    Columbus
1    A00NMAPO   Amazon  Northeast          Maine    Portland
2    A00NMABO   Amazon  Northeast  Massachusetts      Boston
3    A00NNEMA   Amazon  Northeast  New Hampshire  Manchester
4    A00NVEBU   Amazon  Northeast        Vermont  Burlington

In [16]:
# Retailer variable types.
retailer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   RETAILER_ID  110 non-null    object
 1   RETAILER     110 non-null    object
 2   REGION       110 non-null    object
 3   STATE        110 non-null    object
 4   CITY         110 non-null    object
dtypes: object(5)
memory usage: 4.4+ KB

In [17]:
# Sales basics
sales.head()

,ORDER_ID,RETAILER_ID,INVOICE_DATE,MONTH,DAY,YEAR,PRODUCT_ID,PRICE_PER_UNIT,UNITS_SOLD,OPERATING_MARGIN,SALES_METHOD
0,1,A00MOHCO,1/1/2020,1,1,2020,20,50.0,1200,0.5,In-store
1,7,A00MOHCO,1/7/2020,1,7,2020,20,50.0,1250,0.5,In-store
2,13,A00MOHCO,1/25/2020,1,25,2020,20,50.0,1220,0.5,Outlet
3,19,A00MOHCO,1/31/2020,1,31,2020,20,50.0,1200,0.5,Outlet
4,25,A00MOHCO,2/6/2020,2,6,2020,20,60.0,1220,0.5,Outlet

In [18]:
# Sales variable types
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9648 entries, 0 to 9647
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDER_ID          9648 non-null   int64
 1   RETAILER_ID       9648 non-null   object
 2   INVOICE_DATE      9648 non-null   object
 3   MONTH             9648 non-null   int64
 4   DAY               9648 non-null   int64
 5   YEAR              9648 non-null   int64
 6   PRODUCT_ID        9648 non-null   int64
 7   PRICE_PER_UNIT    9646 non-null   float64
 8   UNITS_SOLD        9648 non-null   object
 9   OPERATING_MARGIN  9648 non-null   float64
 10  SALES_METHOD      9648 non-null   object
dtypes: float64(2), int64(5), object(4)
memory usage: 829.3+ KB

## Data Cleaning

## Starting with the Products

In [19]:
# Slit th ecombined Product ID and Product Name column
products[['Product_ID', 'Product_Name']] = products['PRODUCT_ID|PRODUCT_NAME'].str.split('|', expand=True)

In [20]:
# Verify it worked

products.head()

         PRODUCT_ID|PRODUCT_NAME Product_ID               Product_Name
0      020|Men's Street Footwear        020      Men's Street Footwear
1    030|Men's Athletic Footwear        030    Men's Athletic Footwear
2    120|Women's Street Footwear        120    Women's Street Footwear
3  130|Women's Athletic Footwear        130  Women's Athletic Footwear
4              040|Men's Apparel        040              Men's Apparel

In [21]:
# Remove the old column
products.drop('PRODUCT_ID|PRODUCT_NAME', axis=1, inplace=True)

In [22]:
# Verify again
products.head()

  Product_ID               Product_Name
0        020      Men's Street Footwear
1        030    Men's Athletic Footwear
2        120    Women's Street Footwear
3        130  Women's Athletic Footwear
4        040              Men's Apparel

In [23]:
# Checking variable types
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    6 non-null      object
 1   Product_Name  6 non-null      object
dtypes: object(2)
memory usage: 228.0+ bytes

In [24]:
# Convert Product ID to integer (removes leading zeros)
products['Product_ID'] = products['Product_ID'].astype(int)

In [25]:
# Checking work
products.info()
products.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    6 non-null      int64
 1   Product_Name  6 non-null      object
dtypes: int64(1), object(1)
memory usage: 228.0+ bytes

   Product_ID               Product_Name
0          20      Men's Street Footwear
1          30    Men's Athletic Footwear
2         120    Women's Street Footwear
3         130  Women's Athletic Footwear
4          40              Men's Apparel

## Looking at the retailer dataframe it appears to be fairly clean, but will run some additioal checks

In [30]:
# Addional checks of the retailer df
retailer.groupby('RETAILER_ID').size().value_counts()

1    102
2      4
Name: count, dtype: int64

In [35]:
# Looking into why 4 retailer appear twice
retailer[retailer.duplicated('RETAILER_ID', keep=False)]

    RETAILER_ID       RETAILER     REGION       STATE         CITY
63     S00NNENE  Sports Direct  Northeast  New Jersey       Newark
64     S00NNENE  Sports Direct  Northeast    New York     New York
81     W00SARLI        Walmart      South    Arkansas  Little Rock
83     W00STEHO        Walmart      South       Texas      Houston
84     W00SFLOR        Walmart  Southeast     Florida      Orlando
97     W00SARLI      West Gear      South    Arkansas  Little Rock
100    W00STEHO      West Gear      South       Texas      Houston
102    W00SFLOR      West Gear  Southeast     Florida      Orlando

## The retaile dataset contained four retailer_ID values that appeared more than once. These IDs were associated with different retaile names but same gepgraphic location. Nothing removed at this times. Will reevaluate afer the sales dataset is cleaned and during the merge process.

In [31]:
# Addional checks of the retailer df
retailer.duplicated().sum()

np.int64(0)

In [32]:
# Addional Checks
retailer.isnull().sum()

RETAILER_ID    0
RETAILER       0
REGION         0
STATE          0
CITY           0
dtype: int64

In [33]:
# Additional checks
retailer['STATE'].nunique()

50

## Merge Data

## Exploratory Data Analysis

## VP Business Questions